server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.111:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
